update_revenue_share:
  cron: "12 17 * * *"  # Run every day at midnight
  class: "UpdateRevenueShareJob"
  queue: default



reset_posts_viewed_today:
  cron: '12 17 * * *' # Runs every day at midnight
  class: ResetPostsViewedTodayJob
  queue: default