update_revenue_share:
  cron: "0 0 * * *"  # Run every day at midnight
  class: "UpdateRevenueShareJob"
  queue: default



reset_posts_viewed_today:
  cron: '0 0 * * *' # Runs every day at midnight
  class: ResetPostsViewedTodayJob
  queue: default